import type { Triangle } from './types';

export function serializeBinarySTL(triangles: Triangle[]): ArrayBuffer {
  const HEADER_SIZE = 80;
  const TRIANGLE_SIZE = 50; // 12 floats * 4 bytes + 2 bytes attribute
  const bufferSize = HEADER_SIZE + 4 + triangles.length * TRIANGLE_SIZE;
  const buffer = new ArrayBuffer(bufferSize);
  const view = new DataView(buffer);

  // Write header
  const headerStr = 'Binary STL generated by Topo Print';
  for (let i = 0; i < headerStr.length && i < 80; i++) {
    view.setUint8(i, headerStr.charCodeAt(i));
  }

  // Triangle count (uint32 little-endian)
  view.setUint32(HEADER_SIZE, triangles.length, true);

  let offset = HEADER_SIZE + 4;
  for (const tri of triangles) {
    // Normal
    view.setFloat32(offset, tri.normal.x, true); offset += 4;
    view.setFloat32(offset, tri.normal.y, true); offset += 4;
    view.setFloat32(offset, tri.normal.z, true); offset += 4;
    // 3 vertices
    for (const v of tri.vertices) {
      view.setFloat32(offset, v.x, true); offset += 4;
      view.setFloat32(offset, v.y, true); offset += 4;
      view.setFloat32(offset, v.z, true); offset += 4;
    }
    // Attribute byte count
    view.setUint16(offset, 0, true); offset += 2;
  }

  return buffer;
}

export function downloadSTL(buffer: ArrayBuffer, filename: string = 'terrain.stl'): void {
  const blob = new Blob([buffer], { type: 'application/octet-stream' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
